<page>
    <h1>Exceptions</h1>
    <text>
        All PyTgCalls API errors live inside the <code>exceptions</code> subpackage: <code>pytgcalls.exceptions</code>.
    </text>
    <syntax-highlight>
        from pytgcalls.exceptions import GroupCallNotFound

        try:
            ...
        except GroupCallNotFound as e:
            pass
    </syntax-highlight>

    <h2>Deprecation Errors</h2>
    <category>
        <category-title>exception <ref>pytgcalls.exceptions.<b>TooOldPyrogramVersion</b></ref></category-title>
        <subtext>
            Pyrogram version is too old, raised by <docs-ref link="">start()</docs-ref> or <docs-ref link="">run()</docs-ref>.
        </subtext>

        <category-title>exception <ref>pytgcalls.exceptions.<b>TooOldTelethonVersion</b></ref></category-title>
        <subtext>
            Telethon version is too old, raised by <docs-ref link="">start()</docs-ref> or <docs-ref link="">run()</docs-ref>.
        </subtext>
    </category>

    <h2>MtProto Errors</h2>
    <category>
        <category-title>exception <ref>pytgcalls.exceptions.<b>InvalidMtProtoClient</b></ref></category-title>
        <subtext>
            You set an invalid MtProto client, raised by <docs-ref link="">PyTgCalls</docs-ref>.
        </subtext>

        <category-title>exception <ref>pytgcalls.exceptions.<b>NoMtProtoClientSet</b></ref></category-title>
        <subtext>
            An MtProto client isn't set to <docs-ref link="">PyTgCalls</docs-ref>, raised by
            <docs-ref link="">join_group_call()</docs-ref>, <docs-ref link="">leave_group_call()</docs-ref>,
            <docs-ref link="">change_volume_call()</docs-ref>, <docs-ref link="">change_stream()</docs-ref>,
            <docs-ref link="">pause_stream()</docs-ref> and <docs-ref link="">resume_stream()</docs-ref>.
        </subtext>

        <category-title>exception <ref>ntgcalls.<b>RTMPNeeded</b></ref></category-title>
        <subtext>
            Needed an RTMP Stream, raised by <docs-ref link="">join_group_call()</docs-ref>.
        </subtext>
    </category>

    <h2>PyTgCalls Errors</h2>
    <category>
        <category-title>exception <ref>pytgcalls.exceptions.<b>PyTgCallsAlreadyRunning</b></ref></category-title>
        <subtext>
            PyTgCalls client is already running, raised by <docs-ref link="">start()</docs-ref>.
        </subtext>

        <category-title>exception <ref>pytgcalls.exceptions.<b>GroupCallNotFound</b></ref></category-title>
        <subtext>
            Group call not found, raised by <docs-ref link="">get_active_call()</docs-ref>, <docs-ref link="">get_call()</docs-ref>.
        </subtext>

        <category-title>exception <ref>pytgcalls.exceptions.<b>NoActiveGroupCall</b></ref></category-title>
        <subtext>
            No active group call found, raised by <docs-ref link="">join_group_call()</docs-ref>, <docs-ref link="">leave_group_call()</docs-ref>,
            <docs-ref link="">change_volume_call()</docs-ref>.
        </subtext>

        <category-title>exception <ref>pytgcalls.exceptions.<b>NotInGroupCallError</b></ref></category-title>
        <subtext>
            The userbot there isnâ€™t in a group call, raised by <docs-ref link="">leave_group_call()</docs-ref>.
        </subtext>

        <category-title>exception <ref>pytgcalls.exceptions.<b>AlreadyJoinedError</b></ref></category-title>
        <subtext>
            Already joined into group call, raised by <docs-ref link="">join_group_call()</docs-ref>.
        </subtext>

        <category-title>exception <ref>pytgcalls.exceptions.<b>UnMuteNeeded</b></ref></category-title>
        <subtext>
            Needed to unmute the userbot, raised by <docs-ref link="">join_group_call()</docs-ref>.
        </subtext>
    </category>

    <h2>Stream Errors</h2>
    <category>
        <category-title>exception <ref>ntgcalls.<b>NoVideoSourceFound</b></ref></category-title>
        <subtext>
            The stream doesn't have a video, raised by <docs-ref link="">join_group_call()</docs-ref> or <docs-ref link="">change_stream()</docs-ref>.
        </subtext>

        <category-title>exception <ref>ntgcalls.<b>NoAudioSourceFound</b></ref></category-title>
        <subtext>
            The stream doesn't have an audio, raised by <docs-ref link="">join_group_call()</docs-ref> or <docs-ref link="">change_stream()</docs-ref>.
        </subtext>
    </category>

    <h2>CustomApi Errors</h2>
    <category>
        <category-title>exception <ref>ntgcalls.<b>TooManyCustomApiDecorators</b></ref></category-title>
        <subtext>
            Too Many Custom Api Decorators, raised by <docs-ref link="">on_update_custom_api()</docs-ref>.
        </subtext>
    </category>
</page>